using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;

namespace AB.Middleware.HttpRequestLogging
{
    /// <summary>
    /// This middleware emits a single log event per HTTP request, and helps to eliminate alot of the noise generated by the framework
    /// during the beginning and end of an HTTP request.  Recommended to increase log levels for Microsoft namespace events.
    /// </summary>
    public class HttpRequestLoggingMiddleware
    {
        public const string MessageTemplate = "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {ElapsedMilliseconds} ms";

        private readonly ILogger<HttpRequestLoggingMiddleware> _logger;
        private readonly RequestDelegate _next;

        public HttpRequestLoggingMiddleware(RequestDelegate next, ILogger<HttpRequestLoggingMiddleware> logger)
        {
            _next = next ?? throw new ArgumentNullException(nameof(next));
            _logger = logger;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            if (httpContext == null) throw new ArgumentNullException(nameof(httpContext));
            //_logger.LogTrace("ApiVersion {apiVersion} detected", httpContext.GetRequestedApiVersion().ToString());// is this the best place for this?

            var sw = System.Diagnostics.Stopwatch.StartNew();
            try
            {
                await _next(httpContext);
                sw.Stop();

                var statusCode = httpContext.Response?.StatusCode;
                _logger.LogInformation(MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, httpContext.Response.StatusCode, sw.Elapsed.TotalMilliseconds);
            }
            // Never caught, because `LogException()` returns false.
            catch (Exception e) { }

        }
    }
}
