using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.Extensions.Logging;

namespace AB.Middleware.HttpRequestLogging
{
    /// <summary>
    /// This middleware emits a single log event per HTTP request, and helps to eliminate alot of the noise generated by the framework
    /// during the beginning and end of an HTTP request.  It's recommended to increase log levels for Microsoft/AspNetCore namespace events.
    /// Be aware that unhandled errors that flow through this middleware WILL be logged at the <see cref="LogLevel.Information"/> level.
    /// The intent of this middleware is to capture summary information about your request, even in the scenario of an unhandled error.
    /// It does not assume responsibility for global error handling, but will report a <see cref="StatusCodes.Status500InternalServerError"/>.
    /// </summary>
    public class HttpRequestSummaryLoggingMiddleware
    {
        public const string MessageTemplate = "HTTP {RequestMethod} {RequestPath} responded {StatusCode} in {ElapsedMilliseconds} ms";

        private readonly ILogger<HttpRequestSummaryLoggingMiddleware> _logger;
        private readonly RequestDelegate _next;

        public HttpRequestSummaryLoggingMiddleware(RequestDelegate next, ILogger<HttpRequestSummaryLoggingMiddleware> logger)
        {
            _next = next ?? throw new ArgumentNullException(nameof(next));
            _logger = logger;
        }

        public async Task Invoke(HttpContext httpContext)
        {
            if (httpContext == null) throw new ArgumentNullException(nameof(httpContext));
            //_logger.LogTrace("ApiVersion {apiVersion} detected", httpContext.GetRequestedApiVersion().ToString());// is this the best place for this?

            Int64 start = Stopwatch.GetTimestamp();
            try
            {
                await _next(httpContext);
                double elapsedMs = GetElapsedMilliseconds(start, Stopwatch.GetTimestamp());

                int? statusCode = httpContext.Response?.StatusCode;
                _logger.LogInformation(MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, httpContext.Response.StatusCode, elapsedMs);
            }
            // Never caught - LogException returns false.  The 'when' keyword avoids unwinding the stack and reduces perf impact
            // https://www.thomaslevesque.com/2015/06/21/exception-filters-in-c-6/
            catch (Exception e) when (LogException(httpContext, GetElapsedMilliseconds(start, Stopwatch.GetTimestamp()), e)) { }
        }

        private bool LogException(HttpContext httpContext, double elapsedMs, Exception ex)
        {
            _logger.LogInformation(MessageTemplate, httpContext.Request.Method, httpContext.Request.Path, 500, elapsedMs);
            return false;
        }

        private double GetElapsedMilliseconds(long start, long stop)
        {
            return (stop - start) * 1000 / (double)Stopwatch.Frequency;
        }

        private string GetPath(HttpContext httpContext)
        {
            return httpContext.Features.Get<IHttpRequestFeature>()?.RawTarget ?? httpContext.Request.Path.ToString();
        }
    }
}
